# Copyright 2021-2024 Aion Technology LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

####################################################################################################
# Database configuration. This information is generated by the database script and must be copied
# here.
####################################################################################################
variable "db" {
  description = "Configuration for the database. This info should come from the database script."
  type = object({
    class = string
    engine_version = string
    is_protected = bool
    subnet_ids = list(string)
    sg = string
  })
}

####################################################################################################
# General configuration
####################################################################################################
variable "general" {
  description = "General configuration."
  type = object({
    environment = string
    name = string
    region = string
  })

  default = {
    environment = "test"
    name = "unset"
    region = "us-west-2"
  }
}
